export const rightAnswer = "#67A35D"
export const wrongAnswer = "#DC5A4A"
export const mainBackground = "#E8F0F7"
export const roundButtons = "#8B6373"
export const mainFont = "#444444"
export const secondaryFont = "#bbbbbb"
export const listItemBackground = "white"