export const DECK_LIST_STORAGE_KEY = 'KnowItAll:deckList'
export const SCORE_BOARD_STORAGE_KEY = 'KnowItAll:scoreHistory'
export const NOTIFICATION_KEY = 'KnowItAll:notifications'
export const DECK_ALREADY_EXISTS_MESSAGE = 'There is already a deck with that title!'
export const CARD_ALREADY_EXISTS_MESSAGE = 'There is already a card with that title!'